const params=new URLSearchParams(location.search),placeName=(params.get("name")||"我们的地点").trim(),nameElement=document.getElementById("place-name"),description=document.getElementById("place-description"),counter=document.getElementById("place-photo-count"),gallery=document.getElementById("place-gallery");
const aliasGroups=[["上海","shanghai"],["香港","hongkong","hong kong"],["深圳","shenzhen"]];
function normalize(value){return String(value||"").toLowerCase().replace(/[\s\-_.,，。/\\]+/g,"")}
function folderOf(photo){const parts=photo.src.replace(/\\/g,"/").split("/");return parts.length>2?decodeURIComponent(parts[1]):""}
async function allPhotos(){if(location.protocol.startsWith("http")){try{const response=await fetch("/api/photos",{cache:"no-store"});if(response.ok)return(await response.json()).photos}catch{}}return Array.isArray(window.US_PHOTOS)?window.US_PHOTOS:[]}
function matchingFolders(name){const wanted=normalize(name),group=aliasGroups.find(items=>items.some(item=>normalize(item)===wanted));return group||[name]}
function matchesPlace(photo){const folder=normalize(folderOf(photo));return matchingFolders(placeName).some(target=>folder===normalize(target))}
function createPhoto(photo,index){const figure=document.createElement("figure"),img=document.createElement("img"),caption=document.createElement("figcaption"),number=document.createElement("span");figure.style.setProperty("--frame-tilt",`${((index*17)%9-4)*.32}deg`);figure.style.setProperty("--frame-lift",`${index%4===1?28:index%4===3?12:0}px`);img.src=photo.src;img.alt=photo.name;img.loading=index<6?"eager":"lazy";img.addEventListener("load",()=>figure.classList.add(img.naturalWidth>img.naturalHeight*1.12?"landscape":"portrait"),{once:true});caption.textContent=photo.name;number.textContent=String(index+1).padStart(2,"0");figure.append(img,caption,number);return figure}
async function render(){nameElement.textContent=placeName;document.title=`${placeName}｜LuLu & DengDeng`;const photos=(await allPhotos()).filter(matchesPlace);counter.textContent=String(photos.length).padStart(2,"0");if(!photos.length){description.textContent="这里还没有照片。等我们抵达，或从 Us 页面上传同名地址的照片。";gallery.classList.add("empty");gallery.innerHTML="<div><b>MEMORIES ARE WAITING</b><p>属于这里的故事，还在路上。</p><a href=\"us.html\">去添加照片 →</a></div>";return}description.textContent="每一张照片，都是我们一起抵达这里的证明。";photos.forEach((photo,index)=>gallery.appendChild(createPhoto(photo,index)))}
render();
