const STORAGE_KEY="lulu-dengdeng-map-pins",HIDDEN_KEY="lulu-dengdeng-hidden-places",modeLabel=document.getElementById("map-mode"),footprintButton=document.getElementById("add-footprint"),wishButton=document.getElementById("add-wish"),zoomSteps=[2,4,7],zoomNames={2:"世界",4:"区域",7:"城市"};
const map=L.map("offline-map",{center:[23,35],zoom:2,minZoom:2,maxZoom:7,zoomControl:false,attributionControl:false,scrollWheelZoom:true,wheelDebounceTime:45,wheelPxPerZoomLevel:85,doubleClickZoom:false,worldCopyJump:true});
L.tileLayer("offline-tiles/{z}/{x}/{y}.webp",{minZoom:2,maxZoom:7,minNativeZoom:2,maxNativeZoom:4,noWrap:false,keepBuffer:2}).addTo(map);
L.tileLayer("offline-detail-tiles/{z}/{x}/{y}.webp",{minZoom:7,maxZoom:7,minNativeZoom:7,maxNativeZoom:7,noWrap:false,keepBuffer:1,errorTileUrl:"offline-detail-tiles/blank.webp"}).addTo(map);
const memories=[{name:"上海",lat:31.2304,lng:121.4737,page:"shanghai.html"},{name:"香港",lat:22.3193,lng:114.1694,page:"hongkong.html"},{name:"深圳",lat:22.5431,lng:114.0579,page:"shenzhen.html"}];let pins=loadPins(),hiddenPlaces=loadHiddenPlaces(),markers=[],addingType=null,pendingPoint=null,lastDeleted=null;
function loadPins(){try{return(JSON.parse(localStorage.getItem(STORAGE_KEY))||[]).map(pin=>({...pin,type:pin.type||"wish"}))}catch{return[]}}
function loadHiddenPlaces(){try{return new Set(JSON.parse(localStorage.getItem(HIDDEN_KEY))||[])}catch{return new Set()}}
function placeKey(source,place){return`${source}:${place.name}:${Number(place.lat).toFixed(4)}:${Number(place.lng).toFixed(4)}`}
function savePins(){localStorage.setItem(STORAGE_KEY,JSON.stringify(pins));localStorage.setItem(HIDDEN_KEY,JSON.stringify([...hiddenPlaces]));const visibleMemories=memories.filter(item=>!hiddenPlaces.has(placeKey("memory",item))).length,visibleFootprints=(window.USER_FOOTPRINTS||[]).filter(item=>!hiddenPlaces.has(placeKey("footprint",item))).length;document.getElementById("pin-count").textContent=String(visibleMemories+visibleFootprints+pins.length)}
function escapeHtml(text){return text.replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char])}
function icon(type){return L.divIcon({className:"offline-pin-wrap",html:`<div class="offline-pin ${type}"></div>`,iconSize:[24,34],iconAnchor:[12,32],popupAnchor:[0,-29]})}
function addMarker(place,type,page,source,index){const marker=L.marker([place.lat,place.lng],{icon:icon(type),title:place.name,alt:place.name}).addTo(map),memoryPage=`place.html?name=${encodeURIComponent(place.name)}`,action=source==="pending"?"<span>等待确认位置</span>":`<a href="${memoryPage}">打开城市回忆 →</a>`;marker.bindPopup(`<div class="memory-popup"><small>${type==="wish"?"OUR WISH":"OUR FOOTPRINT"}</small><b>${escapeHtml(place.name)}</b>${action}</div>`);marker.on("click",()=>{const current=map.getZoom();if(current<7)map.setView([place.lat,place.lng],current<4?4:7,{animate:true})});if(source!=="pending")marker.on("contextmenu",event=>{L.DomEvent.preventDefault(event.originalEvent);L.DomEvent.stopPropagation(event.originalEvent);if(!confirm(`从地图删除“${place.name}”吗？\n照片文件会保留。`))return;if(source==="pin"){lastDeleted={source,item:{...place},index};pins.splice(index,1)}else{const key=placeKey(source,place);lastDeleted={source:"hidden",key};hiddenPlaces.add(key)}modeLabel.textContent=`已从地图删除 ${place.name}，照片仍保留`;render()});markers.push(marker)}
function render(){markers.forEach(marker=>marker.remove());markers=[];memories.forEach((item,index)=>{if(!hiddenPlaces.has(placeKey("memory",item)))addMarker(item,"footprint",item.page,"memory",index)});(window.USER_FOOTPRINTS||[]).forEach((item,index)=>{if(!hiddenPlaces.has(placeKey("footprint",item)))addMarker(item,"footprint",null,"footprint",index)});pins.forEach((item,index)=>addMarker(item,item.type,null,"pin",index));if(pendingPoint)addMarker({name:"新足迹",...pendingPoint},"footprint pending",null,"pending",-1);savePins()}
function setMode(type){addingType=type;footprintButton.classList.toggle("active",type==="footprint");wishButton.classList.toggle("active",type==="wish");modeLabel.textContent=type?`点击地图添加${type==="footprint"?"绿色足迹":"红色愿望"}`:"点击图钉查看地点";document.getElementById("offline-map-stage").classList.toggle("adding",Boolean(type))}
footprintButton.addEventListener("click",()=>setMode(addingType==="footprint"?null:"footprint"));wishButton.addEventListener("click",()=>setMode(addingType==="wish"?null:"wish"));
map.on("click",event=>{const params=new URLSearchParams(location.search),pending=params.get("pending");if(pending){pendingPoint={lat:event.latlng.lat,lng:event.latlng.lng};document.getElementById("confirm-location").disabled=false;modeLabel.textContent="位置已选择，可以确认足迹";render();return}if(!addingType)return;const name=prompt("给这个地方起一个名字：",addingType==="footprint"?"我们去过的地方":"想和你去的地方");if(name&&name.trim()){pins.push({name:name.trim(),type:addingType,lat:event.latlng.lat,lng:event.latlng.lng});render()}setMode(null)});
document.getElementById("undo-pin").addEventListener("click",()=>{if(lastDeleted){if(lastDeleted.source==="pin")pins.splice(Math.min(lastDeleted.index,pins.length),0,lastDeleted.item);else hiddenPlaces.delete(lastDeleted.key);lastDeleted=null}else if(pins.length)pins.pop();render()});document.getElementById("clear-pins").addEventListener("click",()=>{if(pins.length&&confirm("确定清空所有自定义足迹和愿望吗？")){pins=[];lastDeleted=null;render()}});
function updateZoom(){const current=map.getZoom(),nearest=zoomSteps.reduce((a,b)=>Math.abs(b-current)<Math.abs(a-current)?b:a);document.getElementById("zoom-label").textContent=zoomNames[nearest];document.getElementById("zoom-out").disabled=current<=2;document.getElementById("zoom-in").disabled=current>=7}
document.getElementById("zoom-in").addEventListener("click",()=>{const next=zoomSteps.find(level=>level>map.getZoom());if(next)map.setZoom(next)});document.getElementById("zoom-out").addEventListener("click",()=>{const previous=[...zoomSteps].reverse().find(level=>level<map.getZoom());if(previous)map.setZoom(previous)});map.on("zoomend",updateZoom);updateZoom();
const params=new URLSearchParams(location.search),pendingId=params.get("pending"),pendingAddress=params.get("address");if(pendingId){document.getElementById("pending-guide").hidden=false;document.getElementById("pending-address").textContent=pendingAddress||"新的地点";document.querySelector(".map-actions").hidden=true;modeLabel.textContent="可先放大，再点击地图选择位置";document.getElementById("offline-map-stage").classList.add("adding");document.getElementById("confirm-location").addEventListener("click",async()=>{if(!pendingPoint)return;const button=document.getElementById("confirm-location");button.disabled=true;button.textContent="正在保存…";const response=await fetch("/api/photos/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pendingId,lat:pendingPoint.lat,lng:pendingPoint.lng})});const result=await response.json();if(!response.ok){button.disabled=false;button.textContent="确认足迹并保存照片 →";return alert(result.error||"保存失败")}location.replace("us.html")})}
render();
