const wall = document.getElementById("photo-loop");
const total = document.getElementById("stream-total");
const isManaged = location.protocol === "http:" || location.protocol === "https:";

wall.addEventListener("pointerover",event=>{if(event.target.closest("figure"))wall.classList.add("photo-hovered")});
wall.addEventListener("pointerout",event=>{const figure=event.target.closest("figure");if(figure&&!figure.contains(event.relatedTarget))wall.classList.remove("photo-hovered")});

function seed(text){let value=2166136261;for(const char of text)value=Math.imul(value^char.charCodeAt(0),16777619);return Math.abs(value)}
async function getPhotos(){if(isManaged){try{const response=await fetch("/api/photos",{cache:"no-store"});if(response.ok)return(await response.json()).photos}catch{}}return Array.isArray(window.US_PHOTOS)?window.US_PHOTOS:[]}

async function buildGallery(){const photos=await getPhotos();const ordered=[...photos].sort((a,b)=>seed(a.src)-seed(b.src));const columnCount=matchMedia("(max-width:760px)").matches?3:5;const columns=Array.from({length:columnCount},(_,index)=>{const column=document.createElement("section"),track=document.createElement("div"),set=document.createElement("div");column.className="moving-column";track.className="column-track";set.className="column-set";column.style.setProperty("--column-width",`${index%2?1.06:.94}fr`);track.appendChild(set);column.appendChild(track);wall.appendChild(column);return{track,set,images:[]}});total.textContent=String(ordered.length).padStart(2,"0");
  ordered.forEach((photo,index)=>{const target=columns[index%columnCount],figure=document.createElement("figure"),img=document.createElement("img"),caption=document.createElement("figcaption"),number=document.createElement("span"),remove=document.createElement("button"),random=seed(photo.src);figure.style.setProperty("--tilt",`${(random%31-15)/10}deg`);figure.style.setProperty("--width",`${88+random%15}%`);figure.style.setProperty("--gap",`${7+random%13}px`);figure.style.setProperty("--side",`${random%2?"auto 0 0 auto":"auto auto 0 0"}`);img.src=photo.src;img.alt=photo.name;img.loading="eager";caption.textContent=photo.name.replace(/[（_]/g," ").replace(/[）]/g,"");number.textContent=String(index+1).padStart(2,"0");remove.type="button";remove.className="delete-photo";remove.textContent="删除照片";remove.hidden=!isManaged;remove.addEventListener("click",event=>deletePhoto(event,photo));figure.append(img,caption,number,remove);target.set.appendChild(figure);target.images.push(img)});
  const loaded=columns.flatMap(({images})=>images.map(img=>new Promise(resolve=>{if(img.complete)resolve();else{img.addEventListener("load",resolve,{once:true});img.addEventListener("error",resolve,{once:true})}})));await Promise.all(loaded);columns.forEach(({track,set},index)=>{const copy=set.cloneNode(true);copy.setAttribute("aria-hidden","true");copy.querySelectorAll(".delete-photo").forEach(button=>button.remove());track.appendChild(copy);const distance=set.getBoundingClientRect().height,seconds=Math.max(38,Math.round(distance/(24+index*2)));track.style.setProperty("--column-duration",`${seconds}s`);track.style.setProperty("--column-delay",`${-(seconds*(index+1)/(columnCount+1))}s`);track.classList.add("rolling")});updateCounter(ordered.length)}

async function deletePhoto(event,photo){event.preventDefault();event.stopPropagation();if(!confirm(`确定从 assets 中永久删除“${photo.name}”吗？`))return;const response=await fetch(`/api/photos?path=${encodeURIComponent(photo.src)}`,{method:"DELETE"});const result=await response.json();if(!response.ok)return alert(result.error||"删除失败");location.reload()}
function updateCounter(count){const started=performance.now();function tick(now){const current=Math.floor(((now-started)/2600)%Math.max(1,count))+1;document.getElementById("stream-current").textContent=String(current).padStart(2,"0");requestAnimationFrame(tick)}requestAnimationFrame(tick)}

const form=document.getElementById("upload-form"),fileInput=document.getElementById("photo-file"),addressInput=document.getElementById("photo-address"),fileLabel=document.getElementById("file-label"),status=document.getElementById("upload-status");
fileInput.addEventListener("change",()=>{fileLabel.textContent=fileInput.files[0]?.name||"选择本地照片"});
if(!isManaged){status.textContent="请通过本地管理服务打开页面后上传或删除照片。";form.querySelector("button").disabled=true}
function uploadPhoto(file,address){return new Promise((resolve,reject)=>{const request=new XMLHttpRequest(),url=`/api/photos?address=${encodeURIComponent(address)}&filename=${encodeURIComponent(file.name)}`;request.open("POST",url);request.setRequestHeader("Content-Type",file.type||"application/octet-stream");request.upload.addEventListener("progress",event=>{if(event.lengthComputable){const percent=Math.min(99,Math.round(event.loaded/event.total*100));status.textContent=`正在上传照片… ${percent}%`}});request.addEventListener("load",()=>{let result;try{result=JSON.parse(request.responseText)}catch{reject(new Error(`服务器返回异常（${request.status||"无状态码"}）`));return}if(request.status<200||request.status>=300){reject(new Error(result.error||`上传失败（${request.status}）`));return}resolve(result)});request.addEventListener("error",()=>reject(new Error("无法连接本地照片服务，请确认 127.0.0.1:4173 仍在运行。")));request.addEventListener("abort",()=>reject(new Error("上传已取消。")));request.send(file)})}
form.addEventListener("submit",async event=>{event.preventDefault();const file=fileInput.files[0],address=addressInput.value.trim(),button=form.querySelector("button"),extension=file?.name.split(".").pop()?.toLowerCase();if(!file||!address){status.textContent="请选择照片并填写地址。";return}if(!["jpg","jpeg","png","webp","gif","avif"].includes(extension)){status.textContent="暂不支持这种格式，请选择 JPG、PNG、WEBP、GIF 或 AVIF。";return}if(file.size>25*1024*1024){status.textContent="照片不能超过 25MB。";return}button.disabled=true;status.textContent="正在准备上传… 0%";try{const result=await uploadPhoto(file,address);if(result.needsLocation){status.textContent="照片已暂存，正在前往地图添加足迹…";location.href=`places.html?pending=${encodeURIComponent(result.pendingId)}&address=${encodeURIComponent(result.address)}`;return}status.textContent="照片已保存到现有地址，正在刷新照片墙…";setTimeout(()=>location.reload(),350)}catch(error){status.textContent=error.message||"上传失败，请重试。";button.disabled=false}});
buildGallery();
