name = "luludeng-api"
main = "src/index.js"
compatibility_date = "2026-05-22"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://luludeng.space,https://luludeng-api.13404211257.workers.dev,http://127.0.0.1:4173,http://localhost:4173"

[[d1_databases]]
binding = "DB"
database_name = "luludeng-messages"
database_id = "d8e24a0d-5167-465e-86e9-e47948e69995"
